// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5ua38lwy0DqNZ-ailKa6IqXsgxzMX8A',
    appId: '1:9045995070:web:7ca12e719640f54748eb6f',
    messagingSenderId: '9045995070',
    projectId: 'chatwithme-8d512',
    authDomain: 'chatwithme-8d512.firebaseapp.com',
    storageBucket: 'chatwithme-8d512.appspot.com',
    measurementId: 'G-J4KV2N5F52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcM4uHL5zZYOJwL8hlsuYFb9Gv6wy8Kaw',
    appId: '1:9045995070:android:8467a96eb1b6976148eb6f',
    messagingSenderId: '9045995070',
    projectId: 'chatwithme-8d512',
    storageBucket: 'chatwithme-8d512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Aw4mXGfR3Xhl1DDksYqIKpcImBmN4Hc',
    appId: '1:9045995070:ios:c8ec901df9de9dde48eb6f',
    messagingSenderId: '9045995070',
    projectId: 'chatwithme-8d512',
    storageBucket: 'chatwithme-8d512.appspot.com',
    iosBundleId: 'com.example.chatwithme',
  );
}
